### PR TITLE
handle urllib 2.0 changes

### PR DESCRIPTION
**Pull request by greg12000**
HI,

urllib3 >= 2.0 doesn't define urllib3.util.ssl_.DEFAULT_CIPHERS anymore and this creates an import error in the current gpsoauth code.

This change checks the version and removes the import when not needed 

The removal is documented here: https://urllib3.readthedocs.io/en/stable/changelog.html#removed
"Removed DEFAULT_CIPHERS, HAS_SNI, USE_DEFAULT_SSLCONTEXT_CIPHERS, from the private module urllib3.util.ssl_ (#2168)."

I ran the pre-commit before submiting. One warning related to the google import was still there but I didn't fix it as it wasn't related to teh same issue.

Best,

### CODE REVIEW

**Comment by simon-weber** [comment]
Thanks! Were you able to auth before and after this change? I'd want to check that Google accepts whatever the new ciphers end up being.

**Comment by greg12000** [comment]
I could auth before and after, but with urllib3 > 2.0 I had this error:

Username or password is incorrect (AttributeError("module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'"))

Which is caused by DEFAULT_CIPHERS being removed from urllib3.ssl_ after version 2.0

**Comment by greg12000** [comment]
another solution is to stick with urllib 1.26.x otherwise in the poetry dependencies.

**Comment by simon-weber** [comment]
There's another issue with urllib3 in a child dependency, so I just constrained it for now: https://github.com/simon-weber/gpsoauth/commit/edbba0d4f603126aee0d81172171094836473206

**Comment by simon-weber** [comment]
I guess we should merge this too for when we remove the constraint. I'll just rerun the formatting on master.

**Comment by simon-weber** [comment]
Thanks!

**Pull request merged**
